/**
 * TikZ export.
 *
 * Coordinates stay in document units and the picture carries a single
 * `scale=` option. TikZ applies `scale` to coordinates AND to circle and arc
 * radii, so nothing needs a second conversion. (The `x=`/`y=` options would
 * scale only the coordinates, which is why they are not used here.)
 */

import { round } from '../dom.js';
import { EXPORT_SCALE } from '../render.js';
import { getType } from '../registry.js';
import { toTikz } from '../mathtext.js';
import { axesMapper } from '../types/plots.js';

/** Turns #1f2937 into the six hex digits TikZ wants. */
function hex(colour) {
  const value = String(colour || '').trim();
  if (/^#[0-9a-fA-F]{6}$/.test(value)) return value.slice(1).toUpperCase();
  if (/^#[0-9a-fA-F]{3}$/.test(value)) {
    return value.slice(1).split('').map((digit) => digit + digit).join('').toUpperCase();
  }
  return null;
}

/**
 * Builds the complete TikZ source.
 * options: { widthCm } sets the printed width of the diagram.
 */
export function toTikzSource(doc, _view, { widthCm = 12 } = {}) {
  const scale = round(widthCm / Math.max(0.1, doc.canvas.width), 4);

  const colours = new Map();
  const colourName = (value) => {
    const digits = hex(value);
    if (!digits) return String(value || 'black').replace('#', '');
    if (!colours.has(digits)) colours.set(digits, `c${colours.size}`);
    return colours.get(digits);
  };

  const byId = (id) => doc.elements.find((element) => element.id === id) || null;

  const ctx = {
    P: (x, y) => `(${round(x, 4)},${round(y, 4)})`,
    color: colourName,
    math: (source) => toTikz(source),
    esc: (text) => String(text ?? '').replace(/([%&#_{}$])/g, '\\$1'),
    // EXPORT_SCALE, not the screen zoom: a dot radius must not follow it.
    px: (pixels) => round(pixels / EXPORT_SCALE, 4),
    byId,
    mapper: (axesId) => axesMapper(byId(axesId)),
    scale,
  };

  const body = [];
  const notes = new Set();

  for (const element of doc.elements) {
    let lines;
    try {
      lines = getType(element.type).tikz(element, ctx) || [];
    } catch (error) {
      body.push(`% ${element.id}: the export failed (${error.message})`);
      continue;
    }
    body.push(`% ${element.id} (${element.type})`);
    for (const line of lines) {
      if (line.startsWith('% ') && /usetikzlibrary|usepackage/.test(line)) { notes.add(line); continue; }
      body.push(line);
    }
  }

  const preamble = [...colours.entries()]
    .map(([digits, name]) => `\\definecolor{${name}}{HTML}{${digits}}`);

  const header = [
    `% ${doc.title}`,
    '% Generated by Diagram Studio.',
    '% Preamble:',
    '%   \\usepackage{tikz}',
    ...[...notes].map((note) => `%   ${note.replace('% ', '')}`),
    '',
    ...preamble,
    preamble.length ? '' : null,
    `\\begin{tikzpicture}[scale=${scale}, >=stealth, line join=round, line cap=round]`,
  ].filter((line) => line !== null);

  return [...header, ...body.map((line) => (line.startsWith('%') ? `  ${line}` : `  ${line}`)), '\\end{tikzpicture}', '']
    .join('\n');
}
